name: kt_overlay_window_test
description: Demonstrates how to use the flutter_overlay_window plugin.

publish_to: 'none' 

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  workmanager: ^0.5.1

  flutter_overlay_window:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true